import Head from 'next/head'

export function HomePage(): JSX.Element {
  return (
    <div className="HomePage">
    <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <h1>HomePage</h1>
    </div>
  );
}
