import Head from "next/head";
import { ReactNode } from "react";
import { useChatGptApiKey } from "../../domains/chatGptApiKey/chatGptApiKeyHooks";
import { ChatGptApiKeyForm } from "./ChatGptApiKeyForm";

export function HomePage(): JSX.Element {
  const key = useChatGptApiKey();

  if (key === undefined) {
    return (
      <Frame>
        <></>
      </Frame>
    );
  }

  return (
    <Frame>
      <ChatGptApiKeyForm />
    </Frame>
  );
}

function Frame({ children }: { children: ReactNode }): JSX.Element {
  return (
    <div className="HomePage m-4">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>ChatGPT API practice</h1>
      {children}
    </div>
  );
}
